workspace:
  base: /test
  path: behat-transformation-context

services:
  web:
    image: fpfis/httpd-php-ci:${PHP_VERSION}
    environment:
     - DOCUMENT_ROOT=/test/behat-transformation-context

pipeline:
  composer-install:
    group: prepare
    image: fpfis/httpd-php-ci:${PHP_VERSION}
    volumes:
      - /cache:/cache
    commands:
      - composer install --ansi --no-suggest --no-progress

  composer-update-lowest:
    group: prepare-update
    image: fpfis/httpd-php-ci:${PHP_VERSION}
    volumes:
      - /cache:/cache
    commands:
      - composer update --prefer-lowest --ansi --no-suggest --no-progress
    when:
      matrix:
        COMPOSER_BOUNDARY: lowest

  grumphp:
    group: test
    image: fpfis/httpd-php-ci:${PHP_VERSION}
    commands:
      - ./vendor/bin/grumphp run

  behat:
    group: test
    image: fpfis/httpd-php-ci:${PHP_VERSION}
    commands:
      - ./vendor/bin/behat --strict

matrix:
  PHP_VERSION:
    - 7.2
    - 7.3
  COMPOSER_BOUNDARY:
    - lowest
    - highest
